Clusterwide EditTopology request
picodata/tarantool-operator pull request #8
Opened 2024-11-01 14:39 UTC by dodokek

In order to fix bug, when replicasets appeared in different clusters, EditToplogy is sent to all replicasets at once, instead of sending consequent requests for each replicaset.

2024-11-05 13:51 UTC, lowitea requested changes

2024-11-05 13:51 UTC, lowitea commented on controllers/cluster_controller.go
> +		return ctrl.Result{RequeueAfter: time.Duration(1 * time.Second)}, err
Maybe it's better to set the interval longer?

2024-11-05 13:51 UTC, lowitea commented on controllers/cluster_controller.go
> +		return ctrl.Result{RequeueAfter: time.Duration(60 * time.Second)}, err
It's better to use constants instead of magic numbers.

2024-11-05 13:51 UTC, lowitea commented on controllers/topology/builtin.go
> +				return Replicaset{}, err
It is more efficient to return a reference from a function and a nil value in case of an error

2024-11-05 13:51 UTC, lowitea commented on controllers/topology/builtin.go
> +	return replicasetsValues, nil
Here you need a singular name

2024-11-05 13:51 UTC, lowitea commented on controllers/topology/builtin.go
> +func (s *BuiltInTopologyService) ExecEditTopology(replicasets []Replicaset) (bool, error) {
The name of the function is strange. Two verbs sound awkward together.

2024-11-05 13:51 UTC, lowitea commented on controllers/cluster_controller.go
> +					return ctrl.Result{RequeueAfter: time.Duration(60 * time.Second)}, err
Please use constants for all magic numbers.

2024-11-05 13:51 UTC, lowitea commented on controllers/cluster_controller.go
> +	for _, sts := range stsList.Items {
I think it would be better to move this check loop to a separate function.

2024-11-05 13:51 UTC, lowitea commented on controllers/cluster_controller.go
> +		reqLogger.Info("All replicas in replicaset explored, creating graphql struct")
This comment is not clear without reading the source codes. It's bad.

2024-11-05 13:51 UTC, lowitea commented on controllers/cluster_controller.go
> +		if curReplicaset, err := topologyClient.GetReplicasetValues(replicas, sts.GetName()); err != nil {
nit: Cur is too ambiguous an abbreviation. This is both cursor and current. It is better to use the full version of currentReplicaset.

2024-11-05 13:51 UTC, lowitea commented on controllers/cluster_controller.go
> +		reqLogger.Info("Successfully generated graphQL variables for replicaset: " + sts.GetName())
This comment is not clear without reading the source codes. Please think about those who will read these logs. It won't be just developers.

2024-11-21 11:24 UTC, Kasen approved these changes

2024-11-21 11:24 UTC, Kasen commented on controllers/cluster_controller.go
> +			reqLogger.Info("Failed to fetch topology values from replicaset")
Мне кажется, что это сообщение в лог и то, что в 298 строке не могут находится на одном уровне логирования.

2024-11-21 15:27 UTC, merged